project_dir: 'projects'
project_name: Natural_History_Museum
movies_dir: 'movies'
video_path: 'movies/Natural_History_Museum.mp4'
plot_filename: 'plot.txt'
video_retrieval:
  video_url: 'https://www.youtube.com/watch?v=fdcEKPS6tOQ'
plot_retrieval:
  video_id:
subplot:
  # Use period as default split character to create more natural scene breaks
  # This will create a new scene for each sentence in the plot
  split_char: '.'
voice:
  model_id: 'tts_models/multilingual/multi-dataset/xtts_v2'
  device: cpu
  reference_voice_path: 'voices/sample_voice.wav'
  tts_language: en
  n_audios: 1
frame_sampling:
  # Increased frame sampling for better matching
  n_frames: 1000
frame_ranking:
  model_id: 'clip-ViT-B-32'
  device: cpu
  # Select more frames per subplot for more variety
  n_retrieved_images: 3
  similarity_batch_size: 128
clip:
  # Increased minimum clip length for longer scenes
  min_clip_len: 5
audio_clip:
  # Adjusted volume levels for better audio experience
  clip_volume: 0.08
  voice_volume: 1.2